# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: devcal.proto for package 'devcal'

require 'grpc'
require_relative 'devcal_pb'

module Devcal
  module EventsService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'devcal.EventsService'

      rpc :InsertEvent, ::Devcal::InsertEventParams, ::Devcal::Event
      rpc :GetEvent, ::Devcal::GetEventParams, ::Devcal::Event
      rpc :ListEvents, ::Devcal::ListEventsParams, stream(::Devcal::Event)
      rpc :FindEvents, ::Devcal::FindEventsParams, stream(::Devcal::Event)
      rpc :UpdateEvent, ::Devcal::UpdateEventParams, ::Google::Protobuf::Empty
      rpc :DeleteEvent, ::Devcal::DeleteEventParams, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
