name: Ruby

on:
  push:
    tags:
      - '*'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Push gem to RubyGems.org
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: rubygems/release-gem@v1
